name: Deploy Pages

on:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup Acton
        uses: ton-blockchain/setup-acton@bb72b7a97df8c5203d6778ebaf773690990a09d0 # v1.2.0
        with:
          working-directory: contract

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Audit dependencies
        run: npm audit --omit=dev

      - name: Generate wrappers
        run: npm run gen-wrappers

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build
        env:
          VITE_DEPLOY_ORIGIN: ${{ vars.VITE_DEPLOY_ORIGIN }}
          TONCENTER_MAINNET_API_KEY: ${{ secrets.NOMINATOR_DAPP_MAINNET_API_KEY }}
          TONCENTER_TESTNET_API_KEY: ${{ secrets.NOMINATOR_DAPP_TESTNET_API_KEY }}

      - name: Test
        run: npm run test

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
